### ISSUE TITLE
Tabs Font Size Clipping issue

### ISSUE THREAD

**Issue by kavehsajjadi** [mediachicken/sublimetext-defaultplus-theme#11]
![clipping](https://cloud.githubusercontent.com/assets/2581018/4520465/89088504-4cee-11e4-8bb4-99d77d834891.PNG)

As you can see, the text for the tabs clips, any ideas?

**Comment by phiphou** [comment]
Same issue, Windows 7, with ST2 and ST3.

**Comment by Ouadie** [comment]
Same issue Windows 8

**Comment by mediachicken** [comment]
This issue was fixed in 4cd270. The, the above commit message is out of error. Enjoy v2
