### ISSUE TITLE
How to apply the Theme Options?

### ISSUE THREAD

**Issue by MortimerNeuss** [mediachicken/sublimetext-defaultplus-theme#15]
I dont understand how the theme options can be applied. Where do I have to activate them? Can you also provide a syntax example?

**Comment by mediachicken** [comment]
You place them in your user preferences, the same place where you specified the theme.

Here's a sample of my preferences file


    {
        "color_scheme": "Packages/Color Scheme - Default/Solarized (Dark).tmTheme",
        "dplus_bright_fonts": true,
        "dplus_bright_minimap": true,
        "dplus_bright_status_bar": true,
        "dplus_fat_tabs": false,
        "scroll_past_end": true,
        "tab_size": 4,
        "theme": "DefaultPlus Solarized.sublime-theme",
        "translate_tabs_to_spaces": true,
        "trim_trailing_white_space_on_save": true
    }

**Comment by MortimerNeuss** [comment]
Thank you, that was very enlighten. I was under the impression that I need to toggle them inside the theme itself. Thank you. 

/closed
