### ISSUE TITLE
Sublime Text 3 Support

### ISSUE THREAD

**Issue by caze73** [mediachicken/sublimetext-defaultplus-theme#2]
I've tried to use your theme in Sublime Text 3 but there are some strange color effects in the tab and status bar. Do you plan to create a working version?

Thanks,
Carsten

![bildschirmfoto 2013-12-04 um 22 06 12](https://f.cloud.github.com/assets/6108610/1677432/f60b5350-5d27-11e3-9525-b7e517f1645b.png)

**Comment by mediachicken** [comment]
Hello everybody. I've launched a new branch (v2) which houses all the new changes. This new branch should fix a number of issues, including this one. Try it out and lemme know if your issues are resolved :smile: 

As this is still just a beta release, it doesn't include the theme options yet, but they are coming.

**Comment by caze73** [comment]
There are still some small issues left:

![screenshot](https://cloud.githubusercontent.com/assets/6108610/7077413/defa1bb2-df10-11e4-81f3-c94646019b2c.png)

**Comment by mediachicken** [comment]
I don't understand how... you're on a Retina mac? You can install other themes, and they work fine? Going to look through my files again to see if anything could have gotten messed up.

**Comment by mediachicken** [comment]
And you did clone the repo into the directory named "Theme - DefaultPlus" right? That's the only thing I can imagine that could be happening.

**Comment by caze73** [comment]
Yes, I'm on a Retina Mac. I'm using Sublime Text 3, Build 3083. I've clone the master branch into a folder "Theme - DefaultPlus" into "~/Library/Application Support/Sublime Text 3/Packages/User". Any other information I can help you with?

**Comment by mediachicken** [comment]
Hmm.. All the screenshots seen in the readme are taken from Sublime Text 3, Build 3083. Only difference is I'm on a retina mac.

So just to be clear, the path `~/Library/Application Support/Sublime Text 3/Packages/Theme - DefaultPlus/DefaultPlus/` is the directory that the `.png`assets are located in? I'm scratching my head trying to figure out why they wouldn't be loading. Hopefully I won't have to worry about problems like this when I get it in package control.

**Comment by caze73** [comment]
Yeap, everything is in this directory. Do you know an other theme which I could possible test?

**Comment by caze73** [comment]
Wait, I've got it. My fault. I've checked out into the folder "~/Library/Application Support/Sublime Text 3/Packages/User", but correct is "~/Library/Application Support/Sublime Text 3/Packages". Then everything looks fine. Thanks for your support.

**Comment by mediachicken** [comment]
:+1: good to hear
